[colors.primary]
background = "#000000"

[font]
size = 11.5

[font.bold]
family = "HackNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "HackNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "HackNerdFontMono"
style = "Italic"

[font.normal]
family = "HackNerdFontMono"
style = "Regular"
